version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crud_db
    ports:
      - "3306:3306"
    networks:
      - backend

  app:
    build: .
    container_name: crud-java-app
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "5005:5005" # Porta de depuração
    networks:
      - backend

networks:
  backend:
